server:
  port: 8081
  servlet:
    context-path: '/Culinaryapi-UserService/'

spring:
  application:
    name: Culinaryapi-UserService
  datasource:
    url: jdbc:postgresql://localhost:5432/Culinaryapi-UserService
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
      jdbc:
        lob:
          non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
  rabbitmq:
    addresses: amqps://gxfhiqck:3sivG1zlLvv3W7SWQcK14y010juFScxm@leopard.lmq.cloudamqp.com/gxfhiqck

Culinary:
  broker:
    exchange:
      userEventExchange: Culinary.userevent
      userServiceEventExchange: Culinary.userserviceevent
    queue:
      userEventQueue:
        name: Culinary.userevent.ms.userService
  auth:
    jwt-secret: ZHsOVU5Y6gGU3/S9WZfY5W/Ni6ZixK0I9rZ44MudSRuNYvib+ZoeP/YQNfEvXlDhEgV60Ma8csbcv6ALfOjdyMg==